version: "3"

services:
  server:
    container_name: "ml-product-rest-api"
    build:
      context: ./server
      dockerfile: Dockerfile
    command: "uvicorn ml_api.main:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    restart: always
    volumes:
      - ./volumes/server_data:/data/
      - ./server:/server
    ports:
      - "8006:8000"
    depends_on:
      - postgres_db
    networks:
      - ml-net

  postgres_db:
    image: postgres:13-alpine
    container_name: "ml-product-postgres"
    environment:
      POSTGRES_DB: "ml_project"
      POSTGRES_USER: "userJBH134JHVA23"
      POSTGRES_PASSWORD: "passJHHSFAJ652538HVJKJ"
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - ml-net

  client:
    container_name: "ml-product-client"
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3036:80"

networks:
  ml-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.138.0.0/24
